export const {
    SECRET_JWT_TOKEN,
    SECRET_SESSION_TOKEN,

    NODEMAILER_USER_EMAIL,
    NODEMAILER_USER_PASS,
    NODEMAILER_CLIENT_ID,
    NODEMAILER_CLIENT_SECRET,
    NODEMAILER_REFRESH_TOKEN,
    NODEMAILER_ACCESS_TOKEN,
} = process.env
